import { scrollTopFn } from "./components/scrollTop.js";
import { createPhoneMaskFn } from "./components/maskInput.js";
import { createSliderFn } from "./components/slider.js";
import { createCounterNodeFn } from "./components/counter.js";
import { deleteItemBasketFn } from "./components/deleteItem.js";
import { createAccordionFn } from "./components/accordion.js";
import { modal } from "./components/modal.js";
import { headerFn } from "./components/headerFn.js";
import { sortModal } from "./components/sort.js";
import { cookieModalFn } from "./components/cookie-modal.js";
import { filterCatalogFn } from "./components/filterCatalog.js";

scrollTopFn();
createPhoneMaskFn();
createSliderFn();
createCounterNodeFn();
deleteItemBasketFn();
createAccordionFn();
modal();
headerFn();
sortModal();
cookieModalFn();
filterCatalogFn();